// Site content: one source for the browser (js/site.js) and for the page build (tools/build.js).
// After changing anything here, run:  node tools/build.js
const NUDE = (() => {
  const WA = '34675161314';
  const LANGS = ['es', 'ca', 'en'];

  /* ------------------------------------------------------------------
     Photos (WebP in /img). w/h are the real pixel sizes, so the page reserves the space.
  ------------------------------------------------------------------ */
  const PHOTOS = {
    recepcion: { src: '/img/00-recepcion.webp', w: 960, h: 1200,
      alt: { es: 'Recepción de Nude Beauty Studio, centro de estética en el Eixample de Barcelona', ca: 'Recepció de Nude Beauty Studio, centre d\'estètica a l\'Eixample de Barcelona', en: 'Reception at Nude Beauty Studio, a beauty salon in Eixample, Barcelona' } },
    manicura: { src: '/img/01-manicura.webp', w: 535, h: 713,
      alt: { es: 'Mesa de manicura junto al ventanal en Nude Beauty Studio, Barcelona', ca: 'Taula de manicura al costat del finestral a Nude Beauty Studio, Barcelona', en: 'Manicure desk by the window at Nude Beauty Studio, Barcelona' } },
    tocador: { src: '/img/02-tocador.webp', w: 960, h: 1280,
      alt: { es: 'Tocador de maquillaje con espejo iluminado en Nude Beauty Studio', ca: 'Tocador de maquillatge amb mirall il·luminat a Nude Beauty Studio', en: 'Make-up vanity with lit mirror at Nude Beauty Studio' } },
    cabina: { src: '/img/03-cabina.webp', w: 881, h: 1175,
      alt: { es: 'Cabina de tratamientos faciales en Nude Beauty Studio, Barcelona', ca: 'Cabina de tractaments facials a Nude Beauty Studio, Barcelona', en: 'Facial treatment room at Nude Beauty Studio, Barcelona' } },
    presoterapia: { src: '/img/04-presoterapia.webp', w: 864, h: 1152,
      alt: { es: 'Cabina de presoterapia en Nude Beauty Studio', ca: 'Cabina de pressoteràpia a Nude Beauty Studio', en: 'Pressotherapy room at Nude Beauty Studio' } },
    espera: { src: '/img/05-espera.webp', w: 960, h: 1280,
      alt: { es: 'Zona de espera de Nude Beauty Studio, con sillones verdes', ca: 'Zona d\'espera de Nude Beauty Studio, amb butaques verdes', en: 'Waiting area at Nude Beauty Studio, with green armchairs' } },
    pasillo: { src: '/img/06-pasillo.webp', w: 960, h: 1280,
      alt: { es: 'Pasillo de entrada con el logotipo de Nude Beauty Studio', ca: 'Passadís d\'entrada amb el logotip de Nude Beauty Studio', en: 'Entrance corridor with the Nude Beauty Studio logo' } },
    mapa: { src: '/img/mapa.webp', w: 876, h: 583,
      alt: { es: 'Mapa: Nude Beauty Studio en Carrer de la Diputació 238, junto a Rambla de Catalunya', ca: 'Mapa: Nude Beauty Studio al Carrer de la Diputació 238, al costat de la Rambla de Catalunya', en: 'Map: Nude Beauty Studio at Carrer de la Diputació 238, next to Rambla de Catalunya' } },
  };
  const GALLERY = ['manicura', 'tocador', 'cabina', 'presoterapia', 'espera', 'pasillo'];

  /* ------------------------------------------------------------------
     Service menu. p = price in €, from = "desde", ask = price on request.
  ------------------------------------------------------------------ */
  const HIDRALIPS = { id: 'hidralips', p: 30,
    n: { es: 'Hidralips', ca: 'Hidralips', en: 'Hidralips' },
    d: { es: 'Hidratación de labios con ácido hialurónico.', ca: 'Hidratació de llavis amb àcid hialurònic.', en: 'Lip hydration with hyaluronic acid.' } };

  const MENU = [
    { id: 'faciales',
      n: { es: 'Faciales', ca: 'Facials', en: 'Facials' },
      h: { es: 'Limpieza facial en Barcelona', ca: 'Neteja facial a Barcelona', en: 'Facials in Barcelona' },
      intro: { es: 'Limpiezas faciales profundas, solas o combinadas con dermaplaning, dermapen (microneedling) o radiofrecuencia. La limpieza retira impurezas y células muertas; el dermaplaning elimina además el vello fino, y el dermapen trabaja la piel con microagujas. Si no sabes cuál elegir, escríbenos y te orientamos según tu piel.',
               ca: 'Neteges facials profundes, soles o combinades amb dermaplaning, dermapen (microneedling) o radiofreqüència. La neteja retira impureses i cèl·lules mortes; el dermaplaning elimina a més el borrissol, i el dermapen treballa la pell amb microagulles. Si no saps quina triar, escriu-nos i t\'orientem segons la teva pell.',
               en: 'Deep facial cleanses, on their own or combined with dermaplaning, dermapen (microneedling) or radiofrequency. The cleanse removes impurities and dead cells; dermaplaning also takes off fine facial hair, and dermapen works the skin with micro-needles. Not sure which to choose? Message us and we\'ll guide you based on your skin.' },
      items: [
        { id: 'limpieza', p: 60,
          n: { es: 'Limpieza facial profunda', ca: 'Neteja facial profunda', en: 'Deep facial cleanse' },
          d: { es: 'Tratamiento completo adaptado a tu piel.', ca: 'Tractament complet adaptat a la teva pell.', en: 'A full treatment adapted to your skin.' } },
        { id: 'limpieza-dermaplaning', p: 75,
          n: { es: 'Limpieza facial profunda + dermaplaning', ca: 'Neteja facial profunda + dermaplaning', en: 'Deep facial cleanse + dermaplaning' },
          d: { es: 'Protocolo completo de limpieza con dermaplaning.', ca: 'Protocol complet de neteja amb dermaplaning.', en: 'Full cleansing protocol with dermaplaning.' } },
        { id: 'limpieza-dermapen', p: 90,
          n: { es: 'Limpieza facial profunda + dermapen', ca: 'Neteja facial profunda + dermapen', en: 'Deep facial cleanse + dermapen' },
          d: { es: 'Protocolo completo de limpieza con microneedling.', ca: 'Protocol complet de neteja amb microneedling.', en: 'Full cleansing protocol with microneedling.' } },
        { id: 'limpieza-completa', p: 120,
          n: { es: 'Limpieza facial profunda + dermaplaning + dermapen', ca: 'Neteja facial profunda + dermaplaning + dermapen', en: 'Deep facial cleanse + dermaplaning + dermapen' },
          d: { es: 'El protocolo más completo de la carta.', ca: 'El protocol més complet de la carta.', en: 'The most complete protocol on the menu.' } },
        { id: 'limpieza-radio', p: 70,
          n: { es: 'Limpieza facial profunda + radiofrecuencia', ca: 'Neteja facial profunda + radiofreqüència', en: 'Deep facial cleanse + radiofrequency' },
          d: { es: 'Para afinar e hidratar la piel.', ca: 'Per afinar i hidratar la pell.', en: 'To refine and hydrate the skin.' } },
        { id: 'dermapen', p: 50,
          n: { es: 'Dermapen', ca: 'Dermapen', en: 'Dermapen' },
          d: { es: 'Tratamiento de microneedling.', ca: 'Tractament de microneedling.', en: 'Microneedling treatment.' } },
        { id: 'dermapen-4', p: 180,
          n: { es: '4 sesiones de Dermapen', ca: '4 sessions de Dermapen', en: '4 Dermapen sessions' },
          d: { es: 'Bono de cuatro sesiones de microneedling.', ca: 'Abonament de quatre sessions de microneedling.', en: 'Pack of four microneedling sessions.' } },
        HIDRALIPS,
      ] },
    { id: 'mirada',
      n: { es: 'Pestañas, cejas y labios', ca: 'Pestanyes, celles i llavis', en: 'Lashes, brows & lips' },
      h: { es: 'Cejas, pestañas y labios', ca: 'Celles, pestanyes i llavis', en: 'Brows, lashes and lips' },
      intro: { es: 'Diseño y perfilado de cejas con hilo o con tinte de henna, laminado de cejas y lifting de pestañas con tinte. El lifting curva y oscurece tus propias pestañas, sin extensiones. Hidralips hidrata los labios con ácido hialurónico.',
               ca: 'Disseny i perfilat de celles amb fil o amb tint de henna, laminat de celles i lifting de pestanyes amb tint. El lifting corba i enfosqueix les teves pròpies pestanyes, sense extensions. Hidralips hidrata els llavis amb àcid hialurònic.',
               en: 'Brow design and shaping with threading or henna tint, brow lamination, and lash lift with tint. The lift curls and darkens your own lashes, with no extensions. Hidralips hydrates the lips with hyaluronic acid.' },
      items: [
        { id: 'lifting', p: 45,
          n: { es: 'Lifting de pestañas + tinte', ca: 'Lifting de pestanyes + tint', en: 'Lash lift + tint' } },
        { id: 'cejas-hilo', p: 15,
          n: { es: 'Diseño y perfilado de cejas con hilo', ca: 'Disseny i perfilat de celles amb fil', en: 'Brow design & threading' },
          d: { es: 'Depilación con hilo para una línea limpia y precisa.', ca: 'Depilació amb fil per a una línia neta i precisa.', en: 'Threading for a clean, precise line.' } },
        { id: 'cejas-henna', p: 25,
          n: { es: 'Diseño y perfilado de cejas + henna', ca: 'Disseny i perfilat de celles + henna', en: 'Brow design + henna' },
          d: { es: 'Perfilado de cejas con tinte de henna.', ca: 'Perfilat de celles amb tint de henna.', en: 'Brow shaping with henna tint.' } },
        { id: 'laminado', p: 45,
          n: { es: 'Laminado de cejas', ca: 'Laminat de celles', en: 'Brow lamination' },
          d: { es: 'Ordena y fija el vello en la dirección que quieras.', ca: 'Ordena i fixa el pèl en la direcció que vulguis.', en: 'Sets brow hairs in the direction you want.' } },
        HIDRALIPS,
      ] },
    { id: 'maquillaje',
      n: { es: 'Maquillaje', ca: 'Maquillatge', en: 'Make-up' },
      h: { es: 'Maquillaje de novia y social', ca: 'Maquillatge de núvia i social', en: 'Bridal and occasion make-up' },
      intro: { es: 'Maquillaje profesional para novias y para eventos: bodas, cenas, fiestas o sesiones de fotos. Al reservar, cuéntanos la fecha y el estilo que buscas.',
               ca: 'Maquillatge professional per a núvies i per a esdeveniments: casaments, sopars, festes o sessions de fotos. En reservar, explica\'ns la data i l\'estil que busques.',
               en: 'Professional make-up for brides and for events: weddings, dinners, parties or photo shoots. When you book, tell us the date and the look you have in mind.' },
      items: [
        { id: 'novia', p: 90, n: { es: 'Maquillaje de novia', ca: 'Maquillatge de núvia', en: 'Bridal make-up' } },
        { id: 'social', p: 75, n: { es: 'Maquillaje social', ca: 'Maquillatge social', en: 'Occasion make-up' } },
      ] },
    { id: 'corporal',
      n: { es: 'Corporal', ca: 'Corporal', en: 'Body' },
      h: { es: 'Tratamientos corporales en Barcelona', ca: 'Tractaments corporals a Barcelona', en: 'Body treatments in Barcelona' },
      intro: { es: 'Presoterapia, masajes, drenaje linfático manual e higiene de espalda, además de aparatología corporal: HIFU 12D, radiofrecuencia, ultrasonido, lipoláser frío, láser photon, vacumterapia y electroestimulación. Casi todos se pueden reservar por sesión suelta o en bono de 4 sesiones.',
               ca: 'Pressoteràpia, massatges, drenatge limfàtic manual i higiene d\'esquena, a més d\'aparatologia corporal: HIFU 12D, radiofreqüència, ultrasò, lipolàser fred, làser photon, vacumteràpia i electroestimulació. Gairebé tots es poden reservar per sessió solta o en abonament de 4 sessions.',
               en: 'Pressotherapy, massage, manual lymphatic drainage and back cleanses, plus body devices: HIFU 12D, radiofrequency, ultrasound, cold lipolaser, photon laser, vacuum therapy and electrostimulation. Most can be booked as a single session or as a pack of 4.' },
      items: [
        { id: 'espalda', p: 60,
          n: { es: 'Higiene de espalda', ca: 'Higiene d\'esquena', en: 'Back cleanse' },
          d: { es: 'Limpieza profunda de la piel de la espalda.', ca: 'Neteja profunda de la pell de l\'esquena.', en: 'Deep cleanse for the skin on your back.' } },
        { id: 'espalda-dermaplaning', p: 80,
          n: { es: 'Limpieza de espalda + dermaplaning', ca: 'Neteja d\'esquena + dermaplaning', en: 'Back cleanse + dermaplaning' } },
        { id: 'preso', p: 25,
          n: { es: 'Presoterapia cuerpo entero', ca: 'Pressoteràpia cos sencer', en: 'Full-body pressotherapy' } },
        { id: 'preso-4', p: 100,
          n: { es: '4 sesiones de presoterapia', ca: '4 sessions de pressoteràpia', en: '4 pressotherapy sessions' } },
        { id: 'electro', p: 40,
          n: { es: 'Electroestimulación', ca: 'Electroestimulació', en: 'Electrostimulation' },
          d: { es: 'Estimulación muscular con electrodos.', ca: 'Estimulació muscular amb elèctrodes.', en: 'Muscle stimulation with electrodes.' } },
        { id: 'electro-4', p: 160,
          n: { es: '4 sesiones de electroestimulación', ca: '4 sessions d\'electroestimulació', en: '4 electrostimulation sessions' } },
        { id: 'masaje-descon', p: 50,
          n: { es: 'Masaje descontracturante', ca: 'Massatge descontracturant', en: 'Deep-tissue massage' },
          d: { es: '60 minutos.', ca: '60 minuts.', en: '60 minutes.' } },
        { id: 'masaje-relax', p: 50,
          n: { es: 'Masaje relajante', ca: 'Massatge relaxant', en: 'Relaxing massage' } },
        { id: 'drenaje', p: 60,
          n: { es: 'Drenaje linfático manual', ca: 'Drenatge limfàtic manual', en: 'Manual lymphatic drainage' } },
        { id: 'drenaje-4', p: 240,
          n: { es: '4 sesiones de drenaje linfático manual', ca: '4 sessions de drenatge limfàtic manual', en: '4 manual lymphatic drainage sessions' } },
        { id: 'hifu', p: 90,
          n: { es: 'HIFU 12D', ca: 'HIFU 12D', en: 'HIFU 12D' },
          d: { es: 'Ultrasonido focalizado de alta intensidad, no invasivo. Estimula colágeno y elastina para reafirmar y redefinir contornos, sin cirugía ni tiempo de recuperación. Abdomen, flancos, piernas y brazos.',
               ca: 'Ultrasò focalitzat d\'alta intensitat, no invasiu. Estimula col·lagen i elastina per reafirmar i redefinir contorns, sense cirurgia ni temps de recuperació. Abdomen, flancs, cames i braços.',
               en: 'Non-invasive high-intensity focused ultrasound. Stimulates collagen and elastin to firm and redefine contours, with no surgery or downtime. Abdomen, flanks, legs and arms.' } },
        { id: 'hifu-4', p: 360,
          n: { es: '4 sesiones de HIFU 12D', ca: '4 sessions d\'HIFU 12D', en: '4 HIFU 12D sessions' } },
        { id: 'radio-corp', p: 60,
          n: { es: 'Radiofrecuencia corporal', ca: 'Radiofreqüència corporal', en: 'Body radiofrequency' } },
        { id: 'radio-corp-4', p: 240,
          n: { es: '4 sesiones de radiofrecuencia corporal', ca: '4 sessions de radiofreqüència corporal', en: '4 body radiofrequency sessions' } },
        { id: 'laser-photon', p: 60,
          n: { es: 'Láser photon', ca: 'Làser photon', en: 'Photon laser' } },
        { id: 'laser-photon-4', p: 144,
          n: { es: '4 sesiones de láser photon', ca: '4 sessions de làser photon', en: '4 photon laser sessions' } },
        { id: 'ultrasonido', p: 50,
          n: { es: 'Ultrasonido', ca: 'Ultrasò', en: 'Ultrasound' } },
        { id: 'ultrasonido-4', p: 200,
          n: { es: '4 sesiones de ultrasonido', ca: '4 sessions d\'ultrasò', en: '4 ultrasound sessions' } },
        { id: 'lipolaser', p: 50,
          n: { es: 'Lipoláser frío', ca: 'Lipolàser fred', en: 'Cold lipolaser' } },
        { id: 'lipolaser-4', p: 200,
          n: { es: '4 sesiones de lipoláser frío', ca: '4 sessions de lipolàser fred', en: '4 cold lipolaser sessions' } },
        { id: 'vacum', p: 70,
          n: { es: 'Vacumterapia con radiofrecuencia', ca: 'Vacumteràpia amb radiofreqüència', en: 'Vacuum therapy with radiofrequency' } },
        { id: 'vacum-4', p: 196,
          n: { es: '4 sesiones de vacumterapia con radiofrecuencia', ca: '4 sessions de vacumteràpia amb radiofreqüència', en: '4 vacuum therapy with radiofrequency sessions' } },
      ] },
    { id: 'manos',
      n: { es: 'Manos y pies', ca: 'Mans i peus', en: 'Hands & feet' },
      h: { es: 'Manicura y pedicura en el Eixample', ca: 'Manicura i pedicura a l\'Eixample', en: 'Manicure and pedicure in Eixample' },
      intro: { es: 'Manicura y pedicura; la pedicura completa incluye esmaltado semipermanente. Las reseñas destacan el trabajo al detalle y los consejos para que el esmalte dure.',
               ca: 'Manicura i pedicura; la pedicura completa inclou esmaltat semipermanent. Les ressenyes destaquen la feina al detall i els consells perquè l\'esmalt duri.',
               en: 'Manicure and pedicure; the full pedicure includes gel polish. Reviews highlight the attention to detail and the advice on making the polish last.' },
      items: [
        { id: 'mani', p: 25, from: true, n: { es: 'Manicura', ca: 'Manicura', en: 'Manicure' } },
        { id: 'mani-pedi', p: 50, from: true, n: { es: 'Manicura y pedicura', ca: 'Manicura i pedicura', en: 'Manicure & pedicure' } },
        { id: 'pedi-semi', p: 40, n: { es: 'Pedicura completa con semipermanente', ca: 'Pedicura completa amb semipermanent', en: 'Full pedicure with gel polish' } },
      ] },
  ];

  /* ------------------------------------------------------------------ */
  const T = {
    es: {
      'nav.services': 'Servicios', 'nav.studio': 'El estudio', 'nav.reviews': 'Reseñas', 'nav.visit': 'Cómo llegar',
      'rev.score': '5,0', 'faq.kicker': 'Preguntas frecuentes', 'faq.title': 'Antes de venir.', 'nav.label': 'Principal', 'tabs.label': 'Categorías', 'close': 'Cerrar',
      'hero.kicker': 'Eixample · Barcelona',
      'hero.title': 'Belleza sin escaparate.',
      'hero.sub': 'Estudio de estética en un quinto piso de Diputació 238. Uñas, cejas, pestañas, faciales y tratamientos corporales.',
      'hero.rating': '5,0 en Google · 106 reseñas',
      'cta.book': 'Reservar por WhatsApp', 'cta.menu': 'Ver servicios y precios', 'cta.appt': 'Solo con cita previa',
      'story.kicker': 'Al llegar',
      'story.title': 'Llamas al timbre y subes.',
      'story.p1': 'No busques un rótulo en la calle: es la puerta 6 de la quinta planta. Llamas, subes y entras a tu hora.',
      'story.p2': 'Dentro, paredes blancas, madera clara y plantas. El tocador de maquillaje está junto a un ventanal que da a una fachada modernista.',
      'menu.kicker': 'Servicios', 'menu.title': 'La carta, con precios.',
      'gal.kicker': 'Galería', 'gal.title': 'El estudio, por dentro.', 'gal.soon': 'Foto próximamente',
      'menu.hint': 'Marca lo que te interese y envíanos la selección por WhatsApp. Te respondemos con día y hora.',
      'rev.kicker': 'Reseñas', 'rev.title': 'Lo que cuentan quienes ya han subido.',
      'rev.source': '106 reseñas en Google Maps, todas de cinco estrellas · octubre de 2026',
      'rev.sub': 'Lo que más se repite',
      'rev.1.t': 'El detalle', 'rev.1.d': 'Uñas trabajadas al milímetro y diseños entendidos a la primera.',
      'rev.5.t': 'Las pestañas', 'rev.5.d': 'El lifting es el servicio más comentado: 14 reseñas. La palabra que más se repite es «natural».',
      'rev.6.t': 'La piel', 'rev.6.d': 'De las limpiezas faciales se sale con la piel hidratada y luminosa. Hay quien vuelve cada mes.',
      'rev.q1': 'Manicura', 'rev.q2': 'Lifting de pestañas',
      'rev.2.t': 'El tiempo', 'rev.2.d': 'Nadie trabaja mirando el reloj.',
      'rev.3.t': 'Los consejos', 'rev.3.d': 'Sales con indicaciones para que el semipermanente dure.',
      'rev.4.t': 'Las que repiten', 'rev.4.d': 'Hay quien acaba un bono de presoterapia, compra otro y trae a su tía.',
      'rev.cta': 'Leer las reseñas en Google',
      'visit.kicker': 'Cómo llegar', 'visit.title': 'Junto a Rambla de Catalunya.',
      'visit.floor': '5º piso, 6ª puerta',
      'visit.tip': 'A 5 minutos del metro Passeig de Gràcia (L2, L3, L4).',
      'visit.route': 'Abrir en Google Maps', 'visit.mapcta': 'Ver en Google Maps',
      'foot.legal': 'Aviso legal', 'foot.privacy': 'Privacidad', 'visit.hours': 'Horario',
      'end.title': '¿Te guardamos hora?', 'end.sub': 'Dinos qué quieres hacerte y qué días te van bien.',
      days: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
      closed: 'Cerrado', openNow: 'Abierto ahora', closesAt: 'cierra a las', closedNow: 'Cerrado ahora', opensAt: 'abre', today: 'hoy a las',
      from: 'desde', ask: 'Consultar precio',
      selected: n => n === 1 ? '1 servicio' : n + ' servicios',
      send: 'Enviar', book: 'Reservar por WhatsApp',
      waHello: 'Hola, me gustaría reservar en Nude Beauty Studio.',
      waList: 'Hola, me gustaría reservar en Nude Beauty Studio:', waEnd: '¿Qué disponibilidad tenéis?',
    },
    ca: {
      'nav.services': 'Serveis', 'nav.studio': 'L\'estudi', 'nav.reviews': 'Ressenyes', 'nav.visit': 'Com arribar',
      'rev.score': '5,0', 'faq.kicker': 'Preguntes freqüents', 'faq.title': 'Abans de venir.', 'nav.label': 'Principal', 'tabs.label': 'Categories', 'close': 'Tancar',
      'hero.kicker': 'Eixample · Barcelona',
      'hero.title': 'Bellesa sense aparador.',
      'hero.sub': 'Estudi d\'estètica en un cinquè pis de Diputació 238. Ungles, celles, pestanyes, facials i tractaments corporals.',
      'hero.rating': '5,0 a Google · 106 ressenyes',
      'cta.book': 'Reservar per WhatsApp', 'cta.menu': 'Veure serveis i preus', 'cta.appt': 'Només amb cita prèvia',
      'story.kicker': 'En arribar',
      'story.title': 'Truques al timbre i puges.',
      'story.p1': 'No busquis cap rètol al carrer: és la porta 6 de la cinquena planta. Truques, puges i entres a la teva hora.',
      'story.p2': 'A dins, parets blanques, fusta clara i plantes. El tocador de maquillatge és al costat d\'un finestral que dona a una façana modernista.',
      'menu.kicker': 'Serveis', 'menu.title': 'La carta, amb preus.',
      'gal.kicker': 'Galeria', 'gal.title': 'L\'estudi, per dins.', 'gal.soon': 'Foto properament',
      'menu.hint': 'Marca el que t\'interessi i envia\'ns la selecció per WhatsApp. Et responem amb dia i hora.',
      'rev.kicker': 'Ressenyes', 'rev.title': 'El que expliquen les que ja han pujat.',
      'rev.source': '106 ressenyes a Google Maps, totes de cinc estrelles · octubre de 2026',
      'rev.sub': 'El que més es repeteix',
      'rev.1.t': 'El detall', 'rev.1.d': 'Ungles treballades al mil·límetre i dissenys entesos a la primera.',
      'rev.5.t': 'Les pestanyes', 'rev.5.d': 'El lifting és el servei més comentat: 14 ressenyes. La paraula que més es repeteix és «natural».',
      'rev.6.t': 'La pell', 'rev.6.d': 'De les neteges facials se\'n surt amb la pell hidratada i lluminosa. Hi ha qui torna cada mes.',
      'rev.q1': 'Manicura', 'rev.q2': 'Lifting de pestanyes',
      'rev.2.t': 'El temps', 'rev.2.d': 'Ningú treballa mirant el rellotge.',
      'rev.3.t': 'Els consells', 'rev.3.d': 'Surts amb indicacions perquè el semipermanent duri.',
      'rev.4.t': 'Les que repeteixen', 'rev.4.d': 'Hi ha qui acaba un abonament de pressoteràpia, en compra un altre i hi porta la tieta.',
      'rev.cta': 'Llegir les ressenyes a Google',
      'visit.kicker': 'Com arribar', 'visit.title': 'Al costat de la Rambla de Catalunya.',
      'visit.floor': '5è pis, 6a porta',
      'visit.tip': 'A 5 minuts del metro Passeig de Gràcia (L2, L3, L4).',
      'visit.route': 'Obrir a Google Maps', 'visit.mapcta': 'Veure a Google Maps',
      'foot.legal': 'Avís legal', 'foot.privacy': 'Privacitat', 'visit.hours': 'Horari',
      'end.title': 'Et guardem hora?', 'end.sub': 'Digue\'ns què et vols fer i quins dies et van bé.',
      days: ['Diumenge', 'Dilluns', 'Dimarts', 'Dimecres', 'Dijous', 'Divendres', 'Dissabte'],
      closed: 'Tancat', openNow: 'Obert ara', closesAt: 'tanca a les', closedNow: 'Tancat ara', opensAt: 'obre', today: 'avui a les',
      from: 'des de', ask: 'Consultar preu',
      selected: n => n === 1 ? '1 servei' : n + ' serveis',
      send: 'Enviar', book: 'Reservar per WhatsApp',
      waHello: 'Hola, m\'agradaria reservar a Nude Beauty Studio.',
      waList: 'Hola, m\'agradaria reservar a Nude Beauty Studio:', waEnd: 'Quina disponibilitat teniu?',
    },
    en: {
      'nav.services': 'Services', 'nav.studio': 'The studio', 'nav.reviews': 'Reviews', 'nav.visit': 'Find us',
      'rev.score': '5.0', 'faq.kicker': 'Questions', 'faq.title': 'Before you come.', 'nav.label': 'Main', 'tabs.label': 'Categories', 'close': 'Close',
      'hero.kicker': 'Eixample · Barcelona',
      'hero.title': 'Beauty without a shop window.',
      'hero.sub': 'A beauty studio on the fifth floor of Diputació 238. Nails, brows, lashes, facials and body treatments.',
      'hero.rating': '5.0 on Google · 106 reviews',
      'cta.book': 'Book on WhatsApp', 'cta.menu': 'See services & prices', 'cta.appt': 'By appointment only',
      'story.kicker': 'When you arrive',
      'story.title': 'Ring the bell and come up.',
      'story.p1': 'Don\'t look for a sign on the street: it\'s door 6 on the fifth floor. Ring, come up and walk in at your time.',
      'story.p2': 'Inside: white walls, light wood and plants. The make-up vanity sits by a full-height window facing a modernista façade.',
      'menu.kicker': 'Services', 'menu.title': 'The menu, with prices.',
      'gal.kicker': 'Gallery', 'gal.title': 'Inside the studio.', 'gal.soon': 'Photo coming soon',
      'menu.hint': 'Tick what you\'re interested in and send us the selection on WhatsApp. We\'ll reply with a day and time.',
      'rev.kicker': 'Reviews', 'rev.title': 'What people say once they\'ve been up.',
      'rev.source': '106 reviews on Google Maps, every one five stars · October 2026',
      'rev.sub': 'What comes up most',
      'rev.1.t': 'The detail', 'rev.1.d': 'Nails done to the millimetre, and designs understood first time.',
      'rev.5.t': 'The lashes', 'rev.5.d': 'The lash lift is the most talked-about service: 14 reviews. The word that comes up most is “natural”.',
      'rev.6.t': 'The skin', 'rev.6.d': 'People leave a facial with hydrated, glowing skin. Some come back every month.',
      'rev.q1': 'Manicure', 'rev.q2': 'Lash lift',
      'rev.2.t': 'The time', 'rev.2.d': 'Nobody works with one eye on the clock.',
      'rev.3.t': 'The advice', 'rev.3.d': 'You leave with tips to make your gel polish last.',
      'rev.4.t': 'The regulars', 'rev.4.d': 'One client finished a pressotherapy pack, bought another and brought her aunt.',
      'rev.cta': 'Read the reviews on Google',
      'visit.kicker': 'Find us', 'visit.title': 'Next to Rambla de Catalunya.',
      'visit.floor': '5th floor, door 6',
      'visit.tip': '5 minutes from Passeig de Gràcia metro (L2, L3, L4).',
      'visit.route': 'Open in Google Maps', 'visit.mapcta': 'View on Google Maps',
      'foot.legal': 'Legal notice', 'foot.privacy': 'Privacy', 'visit.hours': 'Opening hours',
      'end.title': 'Shall we save you a slot?', 'end.sub': 'Tell us what you\'d like done and which days suit you.',
      days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      closed: 'Closed', openNow: 'Open now', closesAt: 'closes at', closedNow: 'Closed now', opensAt: 'opens', today: 'today at',
      from: 'from', ask: 'Price on request',
      selected: n => n === 1 ? '1 service' : n + ' services',
      send: 'Send', book: 'Book on WhatsApp',
      waHello: 'Hi, I\'d like to book at Nude Beauty Studio.',
      waList: 'Hi, I\'d like to book at Nude Beauty Studio:', waEnd: 'What availability do you have?',
    },
  };

  // Opening hours in minutes from midnight, index 0 = Sunday
  const HOURS = [null, [600, 1200], [600, 1200], [600, 1200], [600, 1200], [600, 1200], [600, 1080]];

  /* ------------------------------------------------------------------
     Page title and description per language (search results and link previews).
  ------------------------------------------------------------------ */
  const SEO = {
    es: { title: 'Nude Beauty Studio · Centro de estética en el Eixample, Barcelona',
          desc: 'Centro de estética en el Eixample de Barcelona: manicura, cejas, lifting de pestañas, limpieza facial, tratamientos corporales y maquillaje. Solo con cita.' },
    ca: { title: 'Nude Beauty Studio · Centre d\'estètica a l\'Eixample, Barcelona',
          desc: 'Centre d\'estètica a l\'Eixample de Barcelona: manicura, celles, lifting de pestanyes, neteja facial, tractaments corporals i maquillatge. Només amb cita.' },
    en: { title: 'Nude Beauty Studio · Beauty salon in Eixample, Barcelona',
          desc: 'Beauty salon in Barcelona\'s Eixample: manicure, brows, lash lift, facials, body treatments and make-up. By appointment only, booked on WhatsApp.' },
  };

  /* ------------------------------------------------------------------
     FAQ. A question with a: null is not published (page or structured data) until it has an answer.
  ------------------------------------------------------------------ */
  const FAQ = [
    { q: { es: '¿Cómo pido cita?', ca: 'Com demano cita?', en: 'How do I book?' },
      a: { es: 'Por WhatsApp o por teléfono, en el 675 16 13 14. En la carta de servicios puedes marcar lo que te interesa y enviarnos la selección; te respondemos con día y hora.',
           ca: 'Per WhatsApp o per telèfon, al 675 16 13 14. A la carta de serveis pots marcar el que t\'interessa i enviar-nos la selecció; et responem amb dia i hora.',
           en: 'By WhatsApp or phone, on +34 675 16 13 14. In the service menu you can tick what you want and send us the selection; we reply with a day and time.' } },
    { q: { es: '¿Hay que reservar con antelación?', ca: 'Cal reservar amb antelació?', en: 'Do I need to book in advance?' },
      a: { es: 'Sí. Atendemos solo con cita previa, así que escríbenos antes de venir y te decimos la primera hora libre.',
           ca: 'Sí. Atenem només amb cita prèvia, així que escriu-nos abans de venir i et diem la primera hora lliure.',
           en: 'Yes. We work by appointment only, so message us before you come and we\'ll tell you the first free slot.' } },
    { q: { es: '¿Dónde estáis exactamente?', ca: 'On sou exactament?', en: 'Where exactly are you?' },
      a: { es: 'En Carrer de la Diputació 238, 5º piso, 6ª puerta, 08007 Barcelona (Eixample), junto a Rambla de Catalunya y a 5 minutos del metro Passeig de Gràcia (L2, L3, L4). No hay rótulo en la calle: llama al timbre y sube.',
           ca: 'Al Carrer de la Diputació 238, 5è pis, 6a porta, 08007 Barcelona (Eixample), al costat de la Rambla de Catalunya i a 5 minuts del metro Passeig de Gràcia (L2, L3, L4). No hi ha rètol al carrer: truca al timbre i puja.',
           en: 'At Carrer de la Diputació 238, 5th floor, door 6, 08007 Barcelona (Eixample), next to Rambla de Catalunya and 5 minutes from Passeig de Gràcia metro (L2, L3, L4). There is no sign on the street: ring the bell and come up.' } },
    { q: { es: '¿Qué tratamientos faciales hacéis?', ca: 'Quins tractaments facials feu?', en: 'Which facial treatments do you offer?' },
      a: { es: 'Limpieza facial profunda, sola o combinada con dermaplaning, dermapen (microneedling) o radiofrecuencia; dermapen en sesión suelta o en bono de 4 sesiones; e Hidralips para los labios. Los precios están en la carta.',
           ca: 'Neteja facial profunda, sola o combinada amb dermaplaning, dermapen (microneedling) o radiofreqüència; dermapen en sessió solta o en abonament de 4 sessions; i Hidralips per als llavis. Els preus són a la carta.',
           en: 'Deep facial cleanse, on its own or combined with dermaplaning, dermapen (microneedling) or radiofrequency; dermapen as a single session or a pack of 4; and Hidralips for the lips. Prices are in the menu.' } },
    { q: { es: '¿Hacéis maquillaje de novia a domicilio?', ca: 'Feu maquillatge de núvia a domicili?', en: 'Do you do bridal make-up at home or on location?' },
      a: null },
    { q: { es: '¿Qué formas de pago aceptáis?', ca: 'Quines formes de pagament accepteu?', en: 'Which payment methods do you accept?' },
      a: null },
  ];

  return { WA, LANGS, PHOTOS, GALLERY, MENU, T, HOURS, SEO, FAQ };
})();
if (typeof module !== 'undefined') module.exports = NUDE;
